Use get_version(package) instead of get_version(name)
Fixes the following error in './setup.py publish' when package != name:
Traceback (most recent call last):
  File "./setup.py", line 55, in <module>
    args = {'version': get_version(name)}
  File "./setup.py", line 24, in get_version
    init_py = open(os.path.join(package, '__init__.py')).read()
IOError: [Errno 2] No such file or directory: 'django-raise-exception-view/__init__.py'